version: '3'
services:
 flaskapp:
   build: ./web
   restart: on-failure
   expose:
     - "8000"
   volumes:
     - ./web:/home/flask/app/web
   depends_on:
     - redis
     - postgres
   links:
     - redis
     - postgres
   environment:
     FLASK_DEBUG: 1

 redis:
   image: redis:alpine
   restart: on-failure

 nginx:
   build: nginx/
   restart: on-failure
   ports:
     - "80:80"
   depends_on:
     - flaskapp

 postgres:
   restart: on-failure
   image: postgres:alpine
   volumes:
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./postgres/data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: linode123
     POSTGRES_DB: linode
   expose:
     - "5432"
